In [4]:
import pandas as pd
import numpy as np
df1 = pd.read_csv('tables(each table in one csv)/1.csv', sep='\t').T
df2 = pd.read_csv('tables(each table in one csv)/2.csv', sep='\t').T
df3 = pd.read_csv('tables(each table in one csv)/3.csv', sep='\t').T
df4 = pd.read_csv('tables(each table in one csv)/4.csv', sep='\t').T
df5 = pd.read_csv('tables(each table in one csv)/5.csv', sep='\t').T
df6 = pd.read_csv('tables(each table in one csv)/6.csv', sep='\t').T
df7 = pd.read_csv('tables(each table in one csv)/7.csv', sep='\t').T
df8 = pd.read_csv('tables(each table in one csv)/8.csv', sep='\t').T
df9 = pd.read_csv('tables(each table in one csv)/9.csv', sep='\t').T
df10 = pd.read_csv('tables(each table in one csv)/10.csv', sep='\t').T
df11 = pd.read_csv('tables(each table in one csv)/11.csv', sep='\t').T
df12 = pd.read_csv('tables(each table in one csv)/12.csv', sep='\t').T
df13 = pd.read_csv('tables(each table in one csv)/13.csv', sep='\t').T
df14 = pd.read_csv('tables(each table in one csv)/14.csv', sep='\t').T
df15 = pd.read_csv('tables(each table in one csv)/15.csv', sep='\t').T
df16 = pd.read_csv('tables(each table in one csv)/16.csv', sep='\t').T
dfs = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16]
for i in [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16]:
    i.columns = i.iloc[0]
scnd_stap  = []
third_stap = []
lst_merged = []
merged = pd.DataFrame()
for i in range(0, len(dfs), 2):
    two = dfs[i].merge(dfs[i+1], how='outer', left_index=True, right_index=True)
    lst_merged.append(two)
    
for i in range(0, len(lst_merged), 2):
    two = lst_merged[i].merge(lst_merged[i+1], how='outer', left_index=True, right_index=True)
    scnd_stap.append(two)
    
for i in range(0, len(scnd_stap), 2):
    two = scnd_stap[i].merge(scnd_stap[i+1], how='outer', left_index=True, right_index=True)
    third_stap.append(two)

final = third_stap[0].merge(third_stap[1], how='outer', left_index=True, right_index=True)
df = df16.append(df15.append(df14.append(df13.append(df12.append(df11.append(df10.append(df9.append(df8.append(df7.append(df6.append(df5.append(df4.append(df3.append(df1.append(df2)))))))))))))))
df.index = [i.capitalize().strip() for i in df.index]
df.index = [' '.join(i.strip().split()) for i in df.index]
df = df.drop(df.loc['Fiscal year'].index)
cols = df.columns.tolist()
cols = cols[-1:] + cols[:-1]
df = df[cols]
df.replace('-', None, inplace=True)
for i in df.columns[1:]:
    df[i] = df[i].astype('float')
df.to_csv('SUR_2_cleaned.csv')
df

/home/datascince/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

,table,2000-01,2001-02,2002-03,2003-04,2004-05,2005-06,2006-07,2007-08,2008-09,...,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17,2016-17P,2017-18,2017-18P
Milk,LIVESTOCK PRODUCTS,26284.00,27031.00,27811.00,28624.00,29438.00,31970.00,32996.00,34064.00,35160.00,...,37475.00,38617.00,39855.00,41133.00,42454.00,43818.00,45227.00,NaN,NaN,46682.00
Beef,LIVESTOCK PRODUCTS,1010.00,1034.00,1060.00,1087.00,1115.00,1449.00,1498.00,1549.00,1601.00,...,1711.00,1769.00,1829.00,1887.00,1951.00,2017.00,2085.00,NaN,NaN,2155.00
Mutton,LIVESTOCK PRODUCTS,666.00,683.00,702.00,720.00,739.00,554.00,566.00,578.00,590.00,...,616.00,629.00,643.00,657.00,671.00,686.00,701.00,NaN,NaN,717.00
Poultry meat,LIVESTOCK PRODUCTS,339.00,355.00,370.00,378.00,384.00,512.00,554.00,601.00,652.00,...,767.00,834.00,907.00,987.00,1074.00,1170.00,1276.00,NaN,NaN,1391.00
Wool,LIVESTOCK PRODUCTS,39.20,39.40,39.70,39.90,40.00,40.10,40.60,41.00,41.50,...,42.50,43.00,43.60,44.10,44.60,45.10,45.70,NaN,NaN,46.20
Hair,LIVESTOCK PRODUCTS,18.60,19.30,19.90,20.70,20.70,20.30,20.80,21.40,22.00,...,23.20,23.80,24.40,25.10,25.80,26.50,27.20,NaN,NaN,27.90
Bones,LIVESTOCK PRODUCTS,331.40,339.40,347.60,356.20,365.10,633.50,652.50,672.20,692.40,...,735.10,757.50,780.50,802.90,827.20,852.30,878.20,NaN,NaN,904.90
Fats,LIVESTOCK PRODUCTS,123.50,126.50,129.70,132.90,136.30,203.30,209.20,215.30,221.60,...,234.80,241.70,248.80,255.80,263.30,271.00,279.00,NaN,NaN,287.30
Blood,LIVESTOCK PRODUCTS,41.80,42.90,44.00,45.20,45.20,51.40,52.70,54.10,55.40,...,58.30,59.80,61.30,62.80,64.40,66.10,67.80,NaN,NaN,69.50
Eggs (mln.nos.),LIVESTOCK PRODUCTS,7505.00,7679.00,7860.00,8102.00,8529.00,9712.00,10197.00,10711.00,11258.00,...,12857.00,13114.00,13813.00,14556.00,15346.00,16188.00,17083.00,NaN,NaN,18037.00
Skins (mln.nos.),LIVESTOCK PRODUCTS,7.80,7.90,8.20,8.40,8.60,11.40,11.80,12.20,12.60,...,13.50,13.90,14.40,14.90,15.40,15.90,16.40,NaN,NaN,17.00
Hides (mln.nos.),LIVESTOCK PRODUCTS,38.20,39.20,40.30,42.40,42.60,43.30,44.30,45.30,46.30,...,48.50,49.60,50.70,51.90,53.10,54.30,55.50,NaN,NaN,56.80
buffalo,LIVESTOCK POPULATION,23.30,24.00,24.80,25.50,26.30,27.30,28.20,29.00,29.90,...,31.70,32.70,33.70,34.60,35.60,36.60,37.70,NaN,38.8,NaN
cattle,LIVESTOCK POPULATION,22.40,22.80,23.30,23.80,24.20,29.60,30.70,31.80,33.00,...,35.60,36.90,38.30,39.70,41.20,42.80,44.40,NaN,46.1,NaN
goat,LIVESTOCK POPULATION,49.10,50.90,52.80,54.70,56.70,53.80,55.20,56.70,58.30,...,61.50,63.10,64.90,66.60,68.40,70.30,72.20,NaN,74.1,NaN
sheep,LIVESTOCK POPULATION,24.20,24.40,24.60,24.70,24.90,26.50,26.80,27.10,27.40,...,28.10,28.40,28.80,29.10,29.40,29.80,30.10,NaN,30.5,NaN
poultry,LIVESTOCK POPULATION,292.40,330.00,346.10,352.60,372.00,433.80,477.00,518.00,562.00,...,663.00,721.00,785.00,855.00,932.00,1016.00,1108.00,NaN,1210.0,NaN
camels,LIVESTOCK POPULATION,0.80,0.80,0.80,0.70,0.70,0.90,0.90,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.10,NaN,1.1,NaN
asses,LIVESTOCK POPULATION,3.90,3.90,4.10,4.10,4.20,4.30,4.30,4.40,4.50,...,4.70,4.80,4.90,4.90,5.00,5.10,5.20,NaN,5.3,NaN
horses,LIVESTOCK POPULATION,0.30,0.30,0.30,0.30,0.30,0.30,0.30,0.30,0.40,...,0.40,0.40,0.40,0.40,0.40,0.40,0.40,NaN,0.4,NaN
mules,LIVESTOCK POPULATION,0.20,0.20,0.20,0.20,0.30,0.20,0.20,0.20,0.20,...,0.20,0.20,0.20,0.20,0.20,0.20,0.20,NaN,0.2,NaN
procurement,"PROCUREMENT, RELEASES AND STOCKS OF WHEAT",8582.00,4081.00,4045.00,3514.00,3939.00,4514.00,4422.00,3918.00,9200.00,...,6150.00,5792.00,7910.00,5948.00,6139.00,5806.00,6516.00,NaN,NaN,NaN
Releases,"PROCUREMENT, RELEASES AND STOCKS OF WHEAT",5537.00,3376.00,5130.00,4104.00,4500.00,2088.40,6003.00,6320.00,5784.40,...,6404.00,5820.00,6363.00,6149.00,3380.00,4468.10,6516.00,NaN,NaN,NaN
stocks as on 1st may,"PROCUREMENT, RELEASES AND STOCKS OF WHEAT",3552.00,3683.00,992.00,161.00,350.00,2107.40,501.00,136.00,821.90,...,3186.00,3506.00,1681.00,7566.00,6447.00,6284.00,4531.00,NaN,NaN,NaN
Wheat,PROCUREMENT/SUPPORT PRICES OF AGRICULTURAL COM...,300.00,300.00,300.00,350.00,400.00,415.00,425.00,625.00,950.00,...,950.00,1050.00,1200.00,1200.00,1300.00,1300.00,1300.00,NaN,1300.0,NaN
Rice basmati 385,PROCUREMENT/SUPPORT PRICES OF AGRICULTURAL COM...,300.00,300.00,300.00,350.00,400.00,415.00,425.00,625.00,2500.00,...,950.00,1050.00,1200.00,1200.00,1300.00,1300.00,1300.00,NaN,1300.0,NaN
Rice irri-6 (f.a.q),PROCUREMENT/SUPPORT PRICES OF AGRICULTURAL COM...,300.00,300.00,300.00,350.00,400.00,415.00,425.00,625.00,1400.00,...,950.00,1050.00,1200.00,1200.00,1300.00,1300.00,1300.00,NaN,1300.0,NaN
Paddy basmati 385,PROCUREMENT/SUPPORT PRICES OF AGRICULTURAL COM...,385.00,385.00,385.00,400.00,415.00,460.00,425.00,625.00,1250.00,...,950.00,1050.00,1200.00,1200.00,1300.00,1300.00,1300.00,NaN,1300.0,NaN
Paddy basmati super 2000,PROCUREMENT/SUPPORT PRICES OF AGRICULTURAL COM...,460.00,460.00,460.00,485.00,510.00,560.00,425.00,625.00,1500.00,...,950.00,1050.00,1200.00,1200.00,1300.00,1300.00,1300.00,NaN,1300.0,NaN
Paddy irri-6,PROCUREMENT/SUPPORT PRICES OF AGRICULTURAL COM...,205.00,205.00,205.00,215.00,230.00,300.00,306.00,625.00,700.00,...,950.00,1050.00,1200.00,1200.00,1300.00,1300.00,1300.00,NaN,1300.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Total area,LAND UTILIZATION,79.61,79.61,79.61,79.61,79.61,79.61,79.61,79.61,79.61,...,79.61,79.61,79.61,79.61,79.61,79.61,NaN,79.61,NaN,79.61
Reported area,LAND UTILIZATION,59.44,59.33,59.45,59.46,59.48,57.22,57.05,57.08,57.21,...,57.64,57.73,57.79,57.99,57.99,58.00,NaN,57.90,NaN,57.90
Forest area,LAND UTILIZATION,3.77,3.80,4.04,4.01,4.02,4.03,4.19,4.21,4.21,...,4.26,4.26,4.26,4.55,4.54,4.54,NaN,4.55,NaN,4.55
Not available for cultivation,LAND UTILIZATION,24.37,24.31,24.25,24.23,24.39,22.87,22.70,23.41,23.47,...,23.37,23.25,23.06,23.01,23.10,23.04,NaN,23.00,NaN,23.00
Culturable waste,LAND UTILIZATION,9.17,8.95,8.95,9.10,8.94,8.21,8.30,8.19,8.15,...,7.98,8.19,8.21,8.27,8.30,8.29,NaN,8.25,NaN,8.25
Current fallow,LAND UTILIZATION,6.73,6.60,6.61,6.23,6.86,6.72,5.72,4.93,5.04,...,6.38,7.05,7.04,6.68,6.66,6.74,NaN,6.75,NaN,6.75
net area sown,LAND UTILIZATION,15.40,15.67,15.60,15.89,15.27,15.39,16.16,16.34,16.34,...,15.65,14.98,15.22,15.40,15.46,15.39,NaN,15.36,NaN,15.36
Total area cultivated,LAND UTILIZATION,22.13,22.27,22.21,22.12,22.13,22.11,21.87,21.17,21.38,...,22.03,22.03,22.26,22.06,22.10,22.11,NaN,22.06,NaN,22.06
Area sown more than once,LAND UTILIZATION,6.64,6.45,6.25,7.05,7.51,7.74,7.40,7.51,7.78,...,7.07,7.52,7.34,7.76,7.82,7.76,NaN,7.56,NaN,7.56
Total cropped area,LAND UTILIZATION,22.04,22.12,21.85,22.94,22.78,23.13,23.56,23.85,24.12,...,22.72,22.50,22.56,22.16,23.27,23.67,NaN,23.25,NaN,23.25
All major crops,INDEX OF AGRICULTURAL PRODUCTION,93.00,97.00,104.00,107.00,104.00,101.00,117.00,126.00,114.00,...,119.00,123.00,22.56,22.16,23.27,23.67,NaN,23.25,NaN,23.25
Food crops,INDEX OF AGRICULTURAL PRODUCTION,91.20,85.20,91.80,94.90,106.40,107.00,115.00,108.00,124.00,...,120.00,120.00,22.56,22.16,23.27,23.67,NaN,23.25,NaN,23.25
Fibre crops,INDEX OF AGRICULTURAL PRODUCTION,95.00,94.40,90.80,89.40,126.90,116.00,114.00,104.00,105.00,...,102.00,121.00,22.56,22.16,23.27,23.67,NaN,23.25,NaN,23.25
Other crops,INDEX OF AGRICULTURAL PRODUCTION,94.00,103.60,112.10,115.10,101.90,95.60,118.00,138.00,108.00,...,119.00,125.00,22.56,22.16,23.27,23.67,NaN,23.25,NaN,23.25
Wheat,INDEX OF AGRICULTURAL PRODUCTION,94.00,103.60,112.10,115.10,101.90,100.00,109.50,98.50,113.00,...,118.50,110.30,113.80,122.10,117.90,120.50,NaN,125.40,NaN,119.80
Maize,INDEX OF AGRICULTURAL PRODUCTION,94.00,103.60,112.10,115.10,101.90,100.00,99.30,115.90,115.50,...,119.20,139.50,135.70,159.00,158.70,169.50,NaN,197.20,NaN,183.30
Rice,INDEX OF AGRICULTURAL PRODUCTION,94.00,103.60,112.10,115.10,101.90,100.00,98.00,100.30,125.30,...,87.00,111.10,99.80,122.60,126.20,122.60,NaN,123.50,NaN,134.20
Sugarcane,INDEX OF AGRICULTURAL PRODUCTION,94.00,103.60,112.10,115.10,101.90,100.00,122.60,143.10,112.00,...,123.80,130.70,142.70,151.00,140.70,146.60,NaN,169.00,NaN,181.60
Cotton,INDEX OF AGRICULTURAL PRODUCTION,94.00,103.60,112.10,115.10,101.90,100.00,98.70,89.50,90.80,...,88.00,104.40,100.10,98.10,107.20,76.20,NaN,82.00,NaN,91.70
Cropped area (million hectares),BASIC DATA ON AGRICULTURE,22.04,22.12,21.85,22.94,22.78,23.13,23.56,23.85,24.12,...,22.72,22.50,22.56,22.16,23.27,23.67,23.25,NaN,NaN,23.25
Improved seed distribution (000 tonnes),BASIC DATA ON AGRICULTURE,193.80,191.57,172.02,178.77,218.12,226.07,218.60,264.67,314.63,...,331.02,346.38,327.08,359.18,481.00,473.15,428.17,NaN,NaN,476.61
Water ^ availability (maf),BASIC DATA ON AGRICULTURE,134.77,134.63,134.48,134.78,135.68,137.98,137.80,137.80,131.51,...,137.16,135.86,137.51,137.51,138.59,133.00,132.70,NaN,NaN,133.40
Fertilizer offtake (000 n/t),BASIC DATA ON AGRICULTURE,2964.00,2929.00,3020.00,3222.00,3694.04,3804.00,3672.00,3581.00,3711.00,...,3933.00,3861.00,3621.00,4089.00,4316.00,3699.00,5040.00,NaN,NaN,3709.00
Credit disbursed (rs million),BASIC DATA ON AGRICULTURE,44790.00,52314.00,58915.00,73446.00,108733.00,137474.00,168830.00,211561.00,233010.00,...,263022.00,293850.00,336247.00,391353.00,515875.00,598287.00,704488.00,NaN,NaN,569973.00
Tubewells public & private (number in 000),BASIC DATA ON AGRICULTURE,659.30,707.30,769.00,950.10,984.30,999.60,1025.80,1016.10,1070.00,...,1103.40,997.70,1220.40,1317.30,1333.50,1355.50,1361.60,NaN,NaN,NaN
Production of tractors (nos),BASIC DATA ON AGRICULTURE,32553.00,24311.00,27101.00,36059.00,44095.00,49642.00,54431.00,53598.00,60561.00,...,71550.00,48120.00,48871.00,34521.00,45860.00,33883.00,53499.00,NaN,NaN,45325.00
Productoin of meat (000 tonnes),BASIC DATA ON AGRICULTURE,2015.00,2072.00,2132.00,2188.00,2271.00,2515.00,2618.00,2728.00,2843.00,...,3094.00,3232.00,3379.00,3531.00,3696.00,3873.00,4061.00,NaN,NaN,4262.00
Milk (000 tonnes),BASIC DATA ON AGRICULTURE,26284.00,27031.00,27811.00,28624.00,29438.00,31970.00,32986.00,34064.00,35160.00,...,37475.00,38617.00,39855.00,41133.00,42454.00,43818.00,45227.00,NaN,NaN,46682.00
Fish production (000 tonees),BASIC DATA ON AGRICULTURE,629.60,637.80,566.20,573.50,580.60,604.90,640.00,885.00,914.10,...,699.90,724.80,728.80,735.00,765.00,788.00,797.00,NaN,NaN,807.00
Total forest production (000 cu.mtr.),BASIC DATA ON AGRICULTURE,472.00,487.00,266.00,313.00,282.00,265.00,373.00,363.00,347.00,...,352.00,354.00,354.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN